server:
  port: 22100
spring:
  application:
    name: xc-service-base-filesystem
  data:
    mongodb:
      uri:  mongodb://localhost:27017/xc_fs
  http:
    multipart:
        enabled: true
        file-size-threshold: 0
        location:
        max-file-size: 1MB
        max-request-size: 30MB
xuecheng:
    fastdfs:
        connect_timeout_in_seconds: 5
        network_timeout_in_seconds: 30
        charset: UTF-8
        tracker_servers: 192.168.101.65:22122