server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri:  mongodb://localhost:27017/xc_cms
eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/,http://localhost:50102/eureka/}
    instance:
      prefer-ip-address: true
      ip-address: ${IP_ADDRESS:127.0.0.1}
      instance-id: ${spring.application.name}:${server.port}
#freemarker configuration   此处不配置应该不影响运行，测试的模板是从数据库中啦取出来的流
freemarker:
    cache:  false   #关闭模板缓存，方便测试
    settings:
      template_update_delay:  0