server:
  port: ${PORT:50101}
spring:
  application:
     name: xc-govern-center
eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
        defaultZone: ${EUREKA_SERVER:http://localhost:50102/eureka/}
    server:
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 6000
